### ISSUE TITLE
Is this what i am looking for??

### ISSUE THREAD

**Issue by VasilisThePikachu** [kunaakos/tinyntendo#2]
I don't know if this is what I am looking for but I want to use my digispark as an automatic turbo controller for the switch, is this what I need to do this??? [i have made a Reddit post](https://www.reddit.com/r/NintendoSwitch/comments/eqjp4h/can_you_use_a_digispark_as_a_turbo_pro_controller/) if you want a bit more details

Btw is it possible to use this with windows? if not I do have a ubuntu dual boot

if this is what I am looking for I would like instructions about how to do this

**Comment by VasilisThePikachu** [comment]
if this is for something else can you help me get the correct program or code to do this??

**Comment by kunaakos** [comment]
Hi! Sorry for replying late, I wasn't paying attention to github notifications :(
I'm not familiar with the switch, because I don't own one. But if it supports generic USB HID devices, it should work!

There's another project that I just found: https://github.com/wchill/SwitchInputEmulator - this seems to do exactly what you need and seems very neat. My project, for reasons I can't remember - but probably because of hardware limitations of the ATTiny - uses the V-USB library and not LUFA. That one seems tried and tested, so I'd say go for it!

I also found this, so something similar was pulled off, maybe contact the author of this? https://medium.com/better-programming/creating-a-fake-nintendo-switch-controller-to-level-up-my-character-in-world-of-final-fantasy-b50adc269a1e
